function [x] = MAC_VHDL()
% Apertura de archivo VHDL
fid = fopen('MAC.vhd','wt');
fprintf(fid,'library ieee;\n\n');
fprintf(fid,'use IEEE.std_logic_1164.all;\n');
fprintf(fid,'use IEEE.std_logic_unsigned.all;\n\n');
fprintf(fid,'entity MAC is\n');
fprintf(fid,'\tgeneric(\n');
fprintf(fid,'\tN: integer\t:= 8;\n');
fprintf(fid,'\tM: integer\t:= 8;\n');
fprintf(fid,'\tK: integer\t:= 8\n\t);\n');
fprintf(fid,'\tport(\n');
fprintf(fid,'\tCLK  :\tin std_logic;\n');
fprintf(fid,'\tRST  :\tin std_logic;\n');
fprintf(fid,'\tSTP  :\tin std_logic;\n');
fprintf(fid,'\tX    :\tin std_logic_vector(N-1 downto 0);\n');
fprintf(fid,'\tCoef :\tin std_logic_vector(M-1 downto 0);\n');
fprintf(fid,'\tOrden:\tin std_logic_vector(K-1 downto 0);\n');
fprintf(fid,'\tY    :\tout std_logic_vector(N-1 downto 0);\n');
fprintf(fid,'\tI    :\tout std_logic_vector(K-1 downto 0);\n');
fprintf(fid,'\tEOP  :\tout std_logic\n\t);\n');
fprintf(fid,'end MAC;\n\n');
fprintf(fid,'architecture unidadMAC of MAC is\n');
fprintf(fid,'signal Z1 :std_logic_vector(N+M-1 downto 0);\n');
fprintf(fid,'signal Z2 :std_logic_vector(N+M+K-1 downto 0);\n');
fprintf(fid,'signal Z3 :std_logic_vector(N+M+K-1 downto 0);\n');
fprintf(fid,'signal Z4 :std_logic_vector(N+M+K-1 downto 0);\n');
fprintf(fid,'signal Y1 :std_logic_vector(N+M+K-1 downto 0);\n');
fprintf(fid,'signal Q  :std_logic_vector(K-1 downto 0);\n');
fprintf(fid,'signal OPC:std_logic_vector(1 downto 0);\n');
fprintf(fid,'signal H1 :std_logic_vector(1 downto 0);\n');
fprintf(fid,'signal H2 :std_logic;\n');
fprintf(fid,'signal Igual:std_logic;\n');
fprintf(fid,'begin\n\n');
fprintf(fid,'\tIgual <= %c1%c when Q=Orden else %c0%c;\n','''','''','''','''');
fprintf(fid,'\tZ3 <= Z2+Z4;\n');
fprintf(fid,'\tZ2(N+M+K-1 downto N+M) <= (others => Z1(N+M-1));\n');
fprintf(fid,'\tZ2(N+M-1 downto 0) <= Z1;\n');
fprintf(fid,'\tU0: entity work.Multiplicador_nm_ss generic map(N,M) port map(X,Coef,Z1);\n');
fprintf(fid,'\tU1: entity work.Registro_Paralelo_Hold_Clear generic map(N+M+K) port map(CLK,RST,H1,Z3,Z4);\n');
fprintf(fid,'\tU2: entity work.Registro_Paralelo_Hold generic map(N+M+K) port map(CLK,RST,H2,Z4,Y1);\n');
fprintf(fid,'\tU3: entity work.Contador_Ascendente_Hold_Clear generic map(k) port map(CLK,RST,OPC,Q);\n');
fprintf(fid,'\tU4: entity work.FSM_MAC	port map(CLK,RST,STP,Igual,OPC,H1,H2,EOP);\n');	
fprintf(fid,'\tI <= Q;\n');	
fprintf(fid,'\t-- La salida Y depende del formato que estemos trabajando\n');	
fprintf(fid,'\tY <= Y1(28 downto 16);\n');	
fprintf(fid,'end unidadMAC;');
fclose(fid);
x=1;
end